config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'discussions#index'
  resources :discussions do
    resources :posts do
      resources :likes
    end
  end

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth' }
  devise_scope :user do
    get 'users/sign_in', to: 'users/sessions#new'
    get 'users/sign_out', to: 'users/sessions#destroy'
    get 'users/:id', to: 'users#show', as: :user
  end
  resources :topics
end

app/models/discussion.rb
class Discussion < ApplicationRecord
  has_many :posts, dependent: :destroy

  scope :findbytopic, ->(topic_parameter) { where(topic_id: topic_parameter) }
end

app/controllers/discussions_controller.rb
class DiscussionsController < ApplicationController
  skip_before_action :verify_authenticity_token

  # landing page, show all discussions
  def index
    @discussions = Discussion.all
    render :index
  end

  # form for adding new discussion
  def new
    @discussion = Discussion.new
    topics = Topic.all
    render :new
  end

  # create a new discussion
  def create
    @discussion = Discussion.new(discussion_params)
    if @discussion.save
      redirect_to discussions_path
    else
      render :new
    end
  end

  # Update a discussion
  def edit
    @discussion = Discussion.find(params[:id])
    render :edit
  end

  # show a single discussion
  def show
    @discussion = Discussion.find(params[:id])
    render :show
  end

  # Update a discussion
  def update
    @discussion = Discussion.find(params[:id])
    if @discussion.update(discussion_params)
      redirect_to discussions_path
    else
      render :edit
    end
  end

  #  find by topics

  # delete a discussion
  def destroy
    @discussion = Discussion.find(params[:id])
    if current_user && current_user.is_admin?
      @discussion.destroy
      flash[:alert] = 'You deleted a discussion'
    else
      flash[:alert] = 'Only admin can delete discussions'
    end
    redirect_to discussions_path
  end

  private

  def discussion_params
    params.require(:discussion).permit(:title, :topic, :content_body, :likes)
  end
end

app/views/discussions/edit.html.erb
<h1>Edit discussion</h1>

 <% if @discussion.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% @discussion.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %> 

<h3>Change the name of this discussion topic:</h3>
<%= form_for @discussion do |f| %>
<%= f.label :topic %>
<br>
<%= f.collection_select :topic, Topic.order(:id),:id,:name, include_blank: false %>
<br>
<br>
<%= f.label :content_body %>
<br>
<%= f.text_area :content_body, :cols => 40, :rows=> 5 %>
<br>
<br>
<%= f.submit %>
<% end %>

app/views/discussions/index.html.erb
<h1>Welcome to Nerdy.lol!</h1>
<h2>View a discussion on your favorite nerdy topic and add a post, or start a discussion of your own!</h2>

<% if @discussions.any? %>
<% @discussions.each do |discussion|%>
<li><%= link_to discussion.topic, discussion_path(discussion) %></li>
<% end %>
<% else %>
<p> No one has made a discussion yet. </p>
<% end %>

<p><%= link_to "Add new discussion", new_discussion_path %></p>

app/views/discussions/new.html.erb
<h1>New discussion</h1>


<%= form_for @discussion do |f| %>
<%= f.label :topic %>
<br>
<%= f.collection_select :topic, Topic.order(:id),:id,:name, include_blank: false %>
<br>
<br>
<%= f.label :content_body %>
<br>
<%= f.text_area :content_body, :cols => 40, :rows=> 5 %>
<br>
<br>
<%= f.submit %>
<% end %>

app/views/discussions/show.html.erb
  <h4>Some posts about <%= @discussion.topic %>:</h4>


  <% @discussion.posts.each do |post| %>
  <ul>
    <li>
      <%= link_to post.content_body, discussion_post_path(@discussion, post) %>
    </li>
  </ul>
  <% end %>

  <p><%= link_to "Add a post", new_discussion_post_path(@discussion) %></p>

  <p><%= link_to "Edit name of discussion", edit_discussion_path(@discussion) %></p>

  <p><%= link_to "Return to discussions", discussions_path %></p>

  <form action="/discussions/<%= @discussion.id() %>" method="post">
  <input name="_method" type="hidden" value="delete" />

  <button type="submit">Delete discussion</button>
</form>