config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'discussions#index'
  resources :discussions do
    resources :posts do
      resources :likes
    end
  end

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth' }
  devise_scope :user do
    get 'users/sign_in', to: 'users/sessions#new'
    get 'users/sign_out', to: 'users/sessions#destroy'
    get 'users/:id', to: 'users#show', as: :user
  end
  resources :topics
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :discussion
  has_many :likes, dependent: :destroy
  has_one :topic
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :authenticate_user!, only: [:new]

  def new
    @discussion = Discussion.find(params[:discussion_id])
    @post = @discussion.posts.new
    render :new
  end

  def create
    @discussion = Discussion.find(params[:discussion_id])
    @post = @discussion.posts.new(post_params)
    if @post.save
      redirect_to discussion_path(@discussion)
    else
      render :new
    end
  end

  def show
    @discussion = Discussion.find(params[:discussion_id])
    @post = Post.find(params[:id])
    render :show
  end

  def edit
    @discussion = Discussion.find(params[:discussion_id])
    @post = Post.find(params[:id])
    render :edit
  end

  def update
    @post = Post.find(params[:id])
    @discussion = Discussion.find(params[:discussion_id])
    if @post.update(post_params)
      redirect_to discussion_path(@discussion)
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    if current_user && current_user.is_admin?
      @post.destroy
      flash[:alert] = 'You deleted a post'
    else
      flash[:alert] = 'Only admin can delete a post'
    end
    redirect_to discussion_path(@post.discussion)
  end

  private

  def post_params
    params.require(:post).permit(:author, :content_body, :discussion_id)
  end
end

app/views/posts/edit.html.erb
<h1>Edit post:</h1>

 <% if @post.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% @post.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %> 

<%= form_for [@discussion, @post] do |f| %>
  <%= f.label :author %>
  <%= f.text_field :author %>
  <%= f.label :content_body %>
  <%= f.text_field :content_body %>
  <%= f.submit  %>
<% end %>

<p><%= link_to "Return to post", discussion_post_path(@discussion, @post) %></p>

app/views/posts/new.html.erb
<h1>Add a new post to this discussion:</h1>

<% if @post.errors.any? %>
<h3>Please fix these errors:</h3>
<ul>
  <% @post.errors.full_messages.each do |message| %>
  <li><%= message %></li>
  <% end %>
</ul>
<% end %>

<%= form_for [@discussion, @post] do |f| %>
<%= f.label :author %>
<%= f.text_field :author %>
<%= f.label :content_body %>
<%= f.text_field :content_body %>

<p><%= f.submit %></p>
<% end %>

<p><%= link_to "Return to discussion", discussion_path(@discussion) %></p>

app/views/posts/show.html.erb
<h2>Post for <%= @discussion.topic %></h2>

<h4>Posted by <%= @post.author %></h4>
<p> <%= @post.content_body %></p>

<%= button_to 'Like', discussion_post_likes_path(@discussion, @post), method: :post %>

<p><%= link_to "Edit post", edit_discussion_post_path(@discussion, @post) %></p>

<p><%= link_to "Return to discussion", discussion_path(@discussion) %></p>

<p><%= @post.likes.count %> <%= (@post.likes.count) == 1 ? 'Like' : 'Likes'%></p>

<form action="/discussions/<%= @discussion.id() %>/posts/<%= @post.id() %>" method="post">
  <input name="_method" type="hidden" value="delete" />

  <button type="submit">Delete post</button>
</form>